[[main]]
none = "none"



[[main]]
name = "About Us"
weight = 10


[[main]]
name = "US Particle Physics"
pageRef = "us-particle-physics"
parent = "About Us"
identifier = "YDEoepkydb"
weight = 2

[[main]]
name = "Executive Committee"
parent = "About Us"
pageRef = "about"
identifier = "8ljnYPMuWu"
weight = 10


[[main]]
name = "Press"
pageRef = "press"
identifier = "8ljasnYPMuWu"
weight = 15




[[main]]
name = "Contact"
pageRef = "contact"
identifier = "iHXcDfZoHo"
weight = 20

[[main]]
name = "Resources"
weight = 30

[[main]]
name = "Events"
pageRef = "events"
identifier = "iHXcDfZoHo"
weight = 35

[[main]]
name = "Resources"
weight = 30

[[main]]
  name = "Relocation Guide For CERN"
  parent = "Resources"
  pageRef = "relocation"
  weight = 20


[[main]]
name = "Join"
pageRef = "join"
identifier = "iHXcDfZoHodfn"
weight = 35



[[main]]
name = "Donate"
url = "https://www.paypal.com/US/fundraiser/charity/2245513"
identifier = "wPWmG093eT"
weight = 9990



[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/us_lhc"
  weight = 9991

[[main]]
  identifier = "facebook"
  pre = "facebook"
  url = "https://www.facebook.com/pages/USLUA-US-LHC-Users-Association/1576014266009645?ref=aymt_homepage_panel"
  weight = 9992


[[footer]]
none = "none"
